#include "collision_dx.h"
#include "collision_shader.h"
#include "dx_common.h"
#include "dx_profile.h"

#ifdef _MSC_VER
	#include <pix3.h>
#else
	#define PIXBeginEvent(...)
	#define PIXEndEvent(...)
	#define PIX_COLOR(r, g, b) 0
#endif

#include <string.h>

struct dx_state_collision {
	ID3D12RootSignature* root_sig;
	ID3D12PipelineState* pso;
};

extern "C" dx_state_collision* dx_state_collision_create(dx_shared_state* sh) {
	dx_state_collision* s = (dx_state_collision*)calloc(1, sizeof(dx_state_collision));

	D3D12_ROOT_PARAMETER root_params[5] = {};

	// Parameter 0: Constants (register b0)
	root_params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	root_params[0].Constants.ShaderRegister = 0;
	root_params[0].Constants.RegisterSpace = 0;
	root_params[0].Constants.Num32BitValues = 3;
	root_params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 1: rigids SRV (register t0)
	root_params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[1].Descriptor.ShaderRegister = 0;
	root_params[1].Descriptor.RegisterSpace = 0;
	root_params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 2: statics SRV (register t1)
	root_params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[2].Descriptor.ShaderRegister = 1;
	root_params[2].Descriptor.RegisterSpace = 0;
	root_params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 3: pairs UAV (register u0)
	root_params[3].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[3].Descriptor.ShaderRegister = 0;
	root_params[3].Descriptor.RegisterSpace = 0;
	root_params[3].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 4: pair_count UAV (register u1)
	root_params[4].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[4].Descriptor.ShaderRegister = 1;
	root_params[4].Descriptor.RegisterSpace = 0;
	root_params[4].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	D3D12_ROOT_SIGNATURE_DESC rs_desc = {};
	rs_desc.NumParameters = 5;
	rs_desc.pParameters = root_params;

	ID3DBlob* signature = nullptr;
	ID3DBlob* error = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(
		&rs_desc, D3D_ROOT_SIGNATURE_VERSION_1, &signature, &error);
		
	if (FAILED(hr)) {
		if (error) {
			fprintf(stderr, "[dx12] Root Signature Error: %s\n", (char*)error->GetBufferPointer());
			error->Release();
		}
		return s;
	}

	DX_CHECK(sh->device->CreateRootSignature(
		0, signature->GetBufferPointer(), signature->GetBufferSize(), IID_PPV_ARGS(&s->root_sig)));
	s->root_sig->SetName(L"Brute_Force_Root_Sig");
	signature->Release();

	// Create the Pipeline State Object using the byte array generated by dxc
	D3D12_COMPUTE_PIPELINE_STATE_DESC pso_desc = {};
	pso_desc.pRootSignature = s->root_sig;
	pso_desc.CS.pShaderBytecode = collision_shader;
	pso_desc.CS.BytecodeLength = sizeof(collision_shader);

	DX_CHECK(sh->device->CreateComputePipelineState(&pso_desc, IID_PPV_ARGS(&s->pso)));
	s->pso->SetName(L"Brute_Force_Narrow_Phase_PSO");

	return s;
}

extern "C" void dx_state_collision_destroy(dx_state_collision* s) {
	if (!s) return;
	if (s->pso) s->pso->Release();
	if (s->root_sig) s->root_sig->Release();
	free(s);
}

extern "C" dx_collision* dx_run_collision(dx_shared_state* sh, dx_state_collision* state,
										  const dx_shape* rigids, uint32_t rigid_count,
										  const dx_shape* statics, uint32_t static_count,
										  bool statics_changed, uint32_t* out_count) {
	*out_count = 0;
	if (rigid_count == 0) return nullptr;

	size_t cols_needed = sh->d_collisions_size;
	if (cols_needed < 8 * ((size_t)rigid_count + static_count)) {
		cols_needed = 8 * ((size_t)rigid_count + static_count);
	}
	if (cols_needed < 1024) cols_needed = 1024;

	uint32_t count = 0;
	const uint32_t block_size = 256;
	uint32_t grid_size = (rigid_count + block_size - 1) / block_size;
	dx_profile prof = {0};

	for (int attempt = 0; attempt < 2; ++attempt) {
		dx_shared_begin_pass(sh, rigids, rigid_count, statics, static_count, statics_changed,
							 cols_needed, &prof);

		// Compute the maximum capacity using the actual allocated size of the pairs buffer
		uint32_t kernel_max = (sh->d_collisions_size > (size_t)UINT32_MAX)
								  ? UINT32_MAX : (uint32_t)sh->d_collisions_size;

		sh->cmd_list->SetComputeRootSignature(state->root_sig);
		sh->cmd_list->SetPipelineState(state->pso);
		
		uint32_t constants[3] = { rigid_count, static_count, kernel_max };
		sh->cmd_list->SetComputeRoot32BitConstants(0, 3, constants, 0);
		sh->cmd_list->SetComputeRootShaderResourceView(1, sh->d_rigids->GetGPUVirtualAddress());
		if (static_count > 0) {
			sh->cmd_list->SetComputeRootShaderResourceView(2,sh->d_statics->GetGPUVirtualAddress());
		} else {
			// Bind dummy SRV to prevent driver complaints if static_count == 0
			sh->cmd_list->SetComputeRootShaderResourceView(2, sh->d_rigids->GetGPUVirtualAddress());
		}

		sh->cmd_list->SetComputeRootUnorderedAccessView(3,sh->d_collisions->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(4, sh->d_col_count->GetGPUVirtualAddress());

		PIXBeginEvent(sh->cmd_list, PIX_COLOR(0, 255, 0), "Phase: Compute Dispatch");
		sh->cmd_list->Dispatch(grid_size, 1, 1);
		PIXEndEvent(sh->cmd_list);
		dx_profile_step(&prof, sh, "kernel");

		count = dx_shared_execute_and_get_count(sh, static_count, &prof);

		if (count <= kernel_max) break;

		cols_needed = count;
		fprintf(stderr, "[dx12] Info: Capacity exceeded (%u > %u). Re-running with the exact required capacity.\n", count, kernel_max);
	}

	dx_collision* h_cols = nullptr;
	if (count > 0) {
		// Success -> Readback the actual collision pairs
		h_cols = dx_shared_readback_collisions(sh, count, &prof);
		*out_count = count;
	}

	dx_profile_end(&prof, sh);

	static dx_profile_acc prof_acc;
	static bool prof_init = false;
	if (!prof_init) {
		dx_profile_acc_init(&prof_acc);
		prof_init = true;
	}
	dx_profile_log_frame(&prof, "brute"); // log every frame
	dx_profile_log(&prof, &prof_acc, "brute", 10); // log avg in intervals

	return h_cols;
}
