#include "algo_simple_broad_shader.h"
#include "algo_simple_narrow_shader.h"
#include "collision_detection_d3d.h"
#include "dx_profile.h"
#include "shared.h"

#ifdef _MSC_VER
	#include <pix3.h>
#else
	#define PIXBeginEvent(...)
	#define PIXEndEvent(...)
	#define PIX_COLOR(r, g, b) 0
#endif

#include <string.h>

struct dx_potential_pair {
	uint32_t a_index;
	uint32_t b_index;
	uint32_t b_type;
	uint32_t pad;
};

struct dx_state_collision {
	ID3D12RootSignature* root_sig;
	ID3D12PipelineState* pso_broad;
	ID3D12PipelineState* pso_narrow;

	ID3D12Resource* d_potential_pairs;
	size_t d_potential_pairs_size;

	ID3D12Resource* d_pair_count;
	size_t d_pair_count_size;

	ID3D12Resource* rb_pair_count;
	size_t rb_pair_count_size;
};

extern "C" dx_state_collision* dx_state_collision_create(dx_shared_state* sh) {
	dx_state_collision* s = (dx_state_collision*)calloc(1, sizeof(dx_state_collision));

	D3D12_ROOT_PARAMETER root_params[8] = {};

	// Parameter 0: Constants (register b0)
	root_params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
	root_params[0].Constants.ShaderRegister = 0;
	root_params[0].Constants.RegisterSpace = 0;
	root_params[0].Constants.Num32BitValues = 4;
	root_params[0].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 1: rigids SRV (register t0)
	root_params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[1].Descriptor.ShaderRegister = 0;
	root_params[1].Descriptor.RegisterSpace = 0;
	root_params[1].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 2: statics SRV (register t1)
	root_params[2].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[2].Descriptor.ShaderRegister = 1;
	root_params[2].Descriptor.RegisterSpace = 0;
	root_params[2].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 3: potential_pairs_srv SRV (register t2)
	root_params[3].ParameterType = D3D12_ROOT_PARAMETER_TYPE_SRV;
	root_params[3].Descriptor.ShaderRegister = 2;
	root_params[3].Descriptor.RegisterSpace = 0;
	root_params[3].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 4: potential_pairs_uav UAV (register u0)
	root_params[4].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[4].Descriptor.ShaderRegister = 0;
	root_params[4].Descriptor.RegisterSpace = 0;
	root_params[4].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 5: pair_count_uav UAV (register u1)
	root_params[5].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[5].Descriptor.ShaderRegister = 1;
	root_params[5].Descriptor.RegisterSpace = 0;
	root_params[5].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 6: collisions UAV (register u2)
	root_params[6].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[6].Descriptor.ShaderRegister = 2;
	root_params[6].Descriptor.RegisterSpace = 0;
	root_params[6].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	// Parameter 7: col_count_uav UAV (register u3)
	root_params[7].ParameterType = D3D12_ROOT_PARAMETER_TYPE_UAV;
	root_params[7].Descriptor.ShaderRegister = 3;
	root_params[7].Descriptor.RegisterSpace = 0;
	root_params[7].ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

	D3D12_ROOT_SIGNATURE_DESC rs_desc = {};
	rs_desc.NumParameters = 8;
	rs_desc.pParameters = root_params;

	ID3DBlob* signature = nullptr;
	ID3DBlob* error = nullptr;
	HRESULT hr = D3D12SerializeRootSignature(
		&rs_desc, D3D_ROOT_SIGNATURE_VERSION_1, &signature, &error);

	if (FAILED(hr)) {
		if (error) {
			fprintf(stderr, "[dx12] Root Signature Error: %s\n", (char*)error->GetBufferPointer());
			error->Release();
		}
		return s;
	}

	DX_CHECK(sh->device->CreateRootSignature(
		0, signature->GetBufferPointer(), signature->GetBufferSize(), IID_PPV_ARGS(&s->root_sig)));
	s->root_sig->SetName(L"Simple_Root_Sig");
	signature->Release();

	// Create the PSOs using the byte arrays generated by dxc
	D3D12_COMPUTE_PIPELINE_STATE_DESC pso_desc = {};
	pso_desc.pRootSignature = s->root_sig;

	pso_desc.CS.pShaderBytecode = algo_simple_broad_shader;
	pso_desc.CS.BytecodeLength = sizeof(algo_simple_broad_shader);
	DX_CHECK(sh->device->CreateComputePipelineState(&pso_desc, IID_PPV_ARGS(&s->pso_broad)));
	s->pso_broad->SetName(L"Simple_Broad_PSO");

	pso_desc.CS.pShaderBytecode = algo_simple_narrow_shader;
	pso_desc.CS.BytecodeLength = sizeof(algo_simple_narrow_shader);
	DX_CHECK(sh->device->CreateComputePipelineState(&pso_desc, IID_PPV_ARGS(&s->pso_narrow)));
	s->pso_narrow->SetName(L"Simple_Narrow_PSO");

	return s;
}

extern "C" void dx_state_collision_destroy(dx_state_collision* s) {
	if (!s) return;
	if (s->pso_broad) s->pso_broad->Release();
	if (s->pso_narrow) s->pso_narrow->Release();
	if (s->root_sig) s->root_sig->Release();
	if (s->d_potential_pairs) s->d_potential_pairs->Release();
	if (s->d_pair_count) s->d_pair_count->Release();
	if (s->rb_pair_count) s->rb_pair_count->Release();
	free(s);
}

extern "C" dx_collision* dx_run_collision(dx_shared_state* sh, dx_state_collision* state,
										  const dx_shape* rigids, uint32_t rigid_count,
										  const dx_shape* statics, uint32_t static_count,
										  bool statics_changed, uint32_t* out_count) {
	*out_count = 0;
	if (rigid_count == 0) return nullptr;

	size_t cols_needed = sh->d_collisions_size;
	if (cols_needed < 8 * ((size_t)rigid_count + static_count)) {
		cols_needed = 8 * ((size_t)rigid_count + static_count);
	}
	if (cols_needed < 1024) cols_needed = 1024;

	uint32_t count = 0;
	const uint32_t block_size = 256;
	uint32_t grid_size = (rigid_count + block_size - 1) / block_size;
	dx_profile prof = {0};

	for (int attempt = 0; attempt < 2; ++attempt) {
		// Only profile first attempt to not confuse the profiler
		bool enable_profiling = (attempt > 0) ? false : true;
		shared_ensure_buffers(sh, rigid_count, static_count, cols_needed);
		shared_write_inputs(sh->up_rigids, rigids, rigid_count, sh->up_statics, statics,
							static_count, statics_changed);

		// Compute the maximum capacity using the actual allocated size of the pairs buffer
		uint32_t kernel_max = (sh->d_collisions_size > (size_t)UINT32_MAX)
								  ? UINT32_MAX : (uint32_t)sh->d_collisions_size;

		ensure_dx_buffer(sh->device, &state->d_potential_pairs, &state->d_potential_pairs_size,
						 kernel_max, sizeof(dx_potential_pair), D3D12_HEAP_TYPE_DEFAULT,
						 D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS, 1.0f);
		ensure_dx_buffer(sh->device, &state->d_pair_count, &state->d_pair_count_size,
						 1, sizeof(uint32_t), D3D12_HEAP_TYPE_DEFAULT,
						 D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS, 1.0f);
		ensure_dx_buffer(sh->device, &state->rb_pair_count, &state->rb_pair_count_size,
						 1, sizeof(uint32_t), D3D12_HEAP_TYPE_READBACK,
						 D3D12_RESOURCE_FLAG_NONE, 1.0f);

		if (state->d_potential_pairs) state->d_potential_pairs->SetName(L"Potential_Pairs_UAV");

		if (enable_profiling) dx_profile_begin(&prof, sh);
		PIXBeginEvent(sh->cmd_list, PIX_COLOR(255, 0, 0), "Phase: Upload Memory");

		sh->cmd_list->CopyBufferRegion(sh->d_rigids, 0, sh->up_rigids, 0,
									   rigid_count * sizeof(dx_shape));
		if (statics_changed && static_count > 0) {
			sh->cmd_list->CopyBufferRegion(sh->d_statics, 0, sh->up_statics, 0,
										   static_count * sizeof(dx_shape));
		}
		sh->cmd_list->CopyBufferRegion(sh->d_col_count, 0, sh->up_zero, 0, sizeof(uint32_t));
		sh->cmd_list->CopyBufferRegion(state->d_pair_count, 0, sh->up_zero, 0, sizeof(uint32_t));

		// Transition inputs to SRV and outputs to UAV
		D3D12_GLOBAL_BARRIER gb_upload = {};
		gb_upload.SyncBefore = D3D12_BARRIER_SYNC_COPY;
		gb_upload.SyncAfter = D3D12_BARRIER_SYNC_COMPUTE_SHADING;
		gb_upload.AccessBefore = D3D12_BARRIER_ACCESS_COPY_DEST;
		gb_upload.AccessAfter = D3D12_BARRIER_ACCESS_SHADER_RESOURCE |
								D3D12_BARRIER_ACCESS_UNORDERED_ACCESS;

		D3D12_BARRIER_GROUP bg_upload = {};
		bg_upload.Type = D3D12_BARRIER_TYPE_GLOBAL;
		bg_upload.NumBarriers = 1;
		bg_upload.pGlobalBarriers = &gb_upload;

		sh->cmd_list->Barrier(1, &bg_upload);

		PIXEndEvent(sh->cmd_list);
		if (enable_profiling) dx_profile_step(&prof, sh, "upload");

		sh->cmd_list->SetComputeRootSignature(state->root_sig);
		sh->cmd_list->SetPipelineState(state->pso_broad);

		uint32_t constants[4] = { rigid_count, static_count, kernel_max, 0 };
		sh->cmd_list->SetComputeRoot32BitConstants(0, 4, constants, 0);
		sh->cmd_list->SetComputeRootShaderResourceView(1, sh->d_rigids->GetGPUVirtualAddress());
		if (static_count > 0) {
			sh->cmd_list->SetComputeRootShaderResourceView(
				2, sh->d_statics->GetGPUVirtualAddress());
		} else {
			// Bind dummy SRV to prevent driver complaints if static_count == 0
			sh->cmd_list->SetComputeRootShaderResourceView(
				2, sh->d_rigids->GetGPUVirtualAddress());
		}

		sh->cmd_list->SetComputeRootShaderResourceView(
			3, state->d_potential_pairs->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(
			4, state->d_potential_pairs->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(
			5, state->d_pair_count->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(
			6, sh->d_collisions->GetGPUVirtualAddress());
		sh->cmd_list->SetComputeRootUnorderedAccessView(
			7, sh->d_col_count->GetGPUVirtualAddress());

		PIXBeginEvent(sh->cmd_list, PIX_COLOR(0, 255, 0), "Phase: Broad Dispatch");
		sh->cmd_list->Dispatch(grid_size, 1, 1);
		PIXEndEvent(sh->cmd_list);
		if (enable_profiling) dx_profile_step(&prof, sh, "broad");

		D3D12_GLOBAL_BARRIER gb_broad = {};
		gb_broad.SyncBefore = D3D12_BARRIER_SYNC_COMPUTE_SHADING;
		gb_broad.SyncAfter = D3D12_BARRIER_SYNC_COPY | D3D12_BARRIER_SYNC_COMPUTE_SHADING;
		gb_broad.AccessBefore = D3D12_BARRIER_ACCESS_UNORDERED_ACCESS;
		gb_broad.AccessAfter = D3D12_BARRIER_ACCESS_COPY_SOURCE |
							   D3D12_BARRIER_ACCESS_SHADER_RESOURCE;

		D3D12_BARRIER_GROUP bg_broad = {};
		bg_broad.Type = D3D12_BARRIER_TYPE_GLOBAL;
		bg_broad.NumBarriers = 1;
		bg_broad.pGlobalBarriers = &gb_broad;

		sh->cmd_list->Barrier(1, &bg_broad);

		sh->cmd_list->CopyBufferRegion(state->rb_pair_count, 0, state->d_pair_count, 0,
									   sizeof(uint32_t));

		execute_and_wait(sh);

		uint32_t pair_count = 0;
		void* mapped = nullptr;
		state->rb_pair_count->Map(0, nullptr, &mapped);
		pair_count = *(uint32_t*)mapped;
		state->rb_pair_count->Unmap(0, nullptr);

		// The narrow phase can never produce more hits than there are potential pairs, so we only
		// need to check and resize against the pair_count here to guarantee safety.
		if (pair_count > kernel_max) {
			cols_needed = pair_count;
			fprintf(stderr, "[dx12] WARNING: Capacity exceeded (%u > %u). "
							"Re-running with the exact required capacity.\n",
					pair_count, kernel_max);
			continue;
		}

		if (enable_profiling) dx_profile_step(&prof, sh, "gap_narrow");

		if (pair_count > 0) {
			sh->cmd_list->SetComputeRootSignature(state->root_sig);
			sh->cmd_list->SetPipelineState(state->pso_narrow);

			constants[3] = pair_count;
			sh->cmd_list->SetComputeRoot32BitConstants(0, 4, constants, 0);
			sh->cmd_list->SetComputeRootShaderResourceView(1, sh->d_rigids->GetGPUVirtualAddress());
			if (static_count > 0) {
				sh->cmd_list->SetComputeRootShaderResourceView(
					2, sh->d_statics->GetGPUVirtualAddress());
			} else {
				sh->cmd_list->SetComputeRootShaderResourceView(
					2, sh->d_rigids->GetGPUVirtualAddress());
			}

			sh->cmd_list->SetComputeRootShaderResourceView(
				3, state->d_potential_pairs->GetGPUVirtualAddress());
			sh->cmd_list->SetComputeRootUnorderedAccessView(
				4, state->d_potential_pairs->GetGPUVirtualAddress());
			sh->cmd_list->SetComputeRootUnorderedAccessView(
				5, state->d_pair_count->GetGPUVirtualAddress());
			sh->cmd_list->SetComputeRootUnorderedAccessView(
				6, sh->d_collisions->GetGPUVirtualAddress());
			sh->cmd_list->SetComputeRootUnorderedAccessView(
				7, sh->d_col_count->GetGPUVirtualAddress());

			PIXBeginEvent(sh->cmd_list, PIX_COLOR(0, 255, 255), "Phase: Narrow Dispatch");
			uint32_t narrow_grid_size = (pair_count + block_size - 1) / block_size;
			sh->cmd_list->Dispatch(narrow_grid_size, 1, 1);
			PIXEndEvent(sh->cmd_list);
		}

		if (enable_profiling) dx_profile_step(&prof, sh, "narrow");

		D3D12_GLOBAL_BARRIER gb_count = {};
		gb_count.SyncBefore = D3D12_BARRIER_SYNC_COMPUTE_SHADING;
		gb_count.SyncAfter = D3D12_BARRIER_SYNC_COPY;
		gb_count.AccessBefore = D3D12_BARRIER_ACCESS_UNORDERED_ACCESS;
		gb_count.AccessAfter = D3D12_BARRIER_ACCESS_COPY_SOURCE;

		D3D12_BARRIER_GROUP bg_count = {};
		bg_count.Type = D3D12_BARRIER_TYPE_GLOBAL;
		bg_count.NumBarriers = 1;
		bg_count.pGlobalBarriers = &gb_count;

		sh->cmd_list->Barrier(1, &bg_count);

		sh->cmd_list->CopyBufferRegion(sh->rb_col_count, 0, sh->d_col_count, 0, sizeof(uint32_t));

		execute_and_wait(sh);

		count = shared_read_count(sh->rb_col_count);
		break;
	}

	dx_collision* h_cols = nullptr;
	if (count > 0) {
		dx_profile_step(&prof, sh, "gap_readback");
		PIXBeginEvent(sh->cmd_list, PIX_COLOR(0, 0, 255), "Phase: Readback");

		// The command list was reset in execute_and_wait, meaning buffers have implicitly
		// decayed to COMMON access. CopyBufferRegion will implicitly promote it to COPY_SOURCE.
		// Success -> Readback the actual collision pairs
		sh->cmd_list->CopyBufferRegion(sh->rb_collisions, 0, sh->d_collisions, 0,
									   count * sizeof(dx_collision));

		PIXEndEvent(sh->cmd_list);
		dx_profile_step(&prof, sh, "readback");

		execute_and_wait(sh);

		h_cols = shared_read_collisions(sh->rb_collisions, count);
		*out_count = count;
	}

	dx_profile_end(&prof, sh);

	static dx_profile_acc prof_acc;
	static bool prof_init = false;
	if (!prof_init) {
		dx_profile_acc_init(&prof_acc);
		prof_init = true;
	}
	dx_profile_log_frame(&prof, "simple");
	dx_profile_log(&prof, &prof_acc, "simple", 10);

	return h_cols;
}
